version: '3.8'
services:
  fastify_api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src
    command: >
      sh -c "yarn clean-build:api && yarn dev"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/cms_backend?schema=public

  postgres_db:
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cms_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
